#!/usr/bin/env python3
"""Print the active non-secret Quadpod field tuning values."""

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import config  # noqa: E402


FIELD_NAMES = [
    "LOADCELL_REFERENCE_UNIT",
    "SAMPLE_RATE_HZ",
    "VICTOR_NEUTRAL_US",
    "VICTOR_PULL_US",
    "VICTOR_JOG_US",
    "ACTUATOR_PULL_DIRECTION",
    "PULL_TARGET_IN_PER_MIN",
    "PRELOAD_TARGET_LBS",
    "PRELOAD_MIN_LBS",
    "PRELOAD_MAX_LBS",
    "PRELOAD_AUTO_ABORT_LBS",
    "PRELOAD_STABILITY_SECONDS",
    "PRELOAD_AUTO_TIMEOUT_SECONDS",
    "PRELOAD_AUTO_SPEED_PERCENT",
    "PRELOAD_AUTO_MIN_PULSE_SECONDS",
    "PRELOAD_AUTO_PULSE_SECONDS",
    "PRELOAD_AUTO_PULSE_CHECK_SECONDS",
    "PRELOAD_AUTO_DIRECT_LOAD_READ",
    "PRELOAD_AUTO_STOP_DURING_LOAD_READ",
    "PRELOAD_AUTO_CONTROL_CONFIRM_SAMPLES",
    "PRELOAD_AUTO_CONTROL_SPIKE_DELTA_LBS",
    "PRELOAD_AUTO_CONTROL_CONFIRM_MAX_RANGE_LBS",
    "PRELOAD_AUTO_CONTROL_HARD_SPIKE_LBS",
    "PRELOAD_AUTO_CONTROL_SPIKE_RETRY_SECONDS",
    "PRELOAD_AUTO_DOWN_PULSE_SECONDS",
    "PRELOAD_AUTO_SETTLE_SECONDS",
    "PRELOAD_AUTO_SETTLE_MAX_SECONDS",
    "PRELOAD_AUTO_TARGET_LBS",
    "PRELOAD_AUTO_PREDICT_STOP_LBS",
    "PRELOAD_AUTO_PREDICT_LOOKAHEAD_SECONDS",
    "PRELOAD_AUTO_RATE_WINDOW_SECONDS",
    "PRELOAD_AUTO_MAX_RISE_RATE_LBS_PER_SECOND",
    "PRELOAD_AUTO_COARSE_MAX_DELTA_LBS",
    "PRELOAD_AUTO_APPROACH_MAX_DELTA_LBS",
    "PRELOAD_AUTO_FINAL_MAX_DELTA_LBS",
    "PRELOAD_AUTO_CONTACT_DELTA_LBS",
    "PRELOAD_AUTO_CONTACT_MAX_DELTA_LBS",
    "PRELOAD_AUTO_CONTACT_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTACT_PULSE_SECONDS",
    "PRELOAD_AUTO_CONTACT_SETTLE_SECONDS",
    "PRELOAD_AUTO_CONTACT_SETTLE_MAX_SECONDS",
    "PRELOAD_AUTO_MIN_STOP_MARGIN_LBS",
    "PRELOAD_AUTO_MAX_STOP_MARGIN_LBS",
    "PRELOAD_AUTO_COAST_MARGIN_SCALE",
    "PRELOAD_AUTO_ADAPTIVE_PULSE_MIN_SCALE",
    "PRELOAD_AUTO_ADAPTIVE_SPEED_MIN_PERCENT",
    "PRELOAD_AUTO_APPROACH_DISTANCE_LBS",
    "PRELOAD_AUTO_COARSE_UNTIL_LBS",
    "PRELOAD_AUTO_COARSE_SETTLE_SECONDS",
    "PRELOAD_AUTO_COARSE_SETTLE_MAX_SECONDS",
    "PRELOAD_AUTO_APPROACH_SETTLE_UNTIL_LBS",
    "PRELOAD_AUTO_APPROACH_SETTLE_SECONDS",
    "PRELOAD_AUTO_APPROACH_SETTLE_MAX_SECONDS",
    "PRELOAD_AUTO_APPROACH_SETTLE_DELTA_LBS",
    "PRELOAD_AUTO_STABLE_WINDOW_SECONDS",
    "PRELOAD_AUTO_STABLE_DELTA_LBS",
    "PRELOAD_AUTO_IN_BAND_END_SECONDS",
    "PRELOAD_AUTO_DRIFT_WINDOW_SECONDS",
    "PRELOAD_AUTO_DRIFT_MAX_DROP_LBS",
    "PRELOAD_AUTO_DRIFT_WARN_SECONDS",
    "PRELOAD_AUTO_TRACE_MAX_ENTRIES",
    "FAILURE_DROP_LBS",
    "FAILURE_DROP_PERCENT",
    "FAILURE_CONFIRM_SAMPLES",
    "FAILURE_MIN_PEAK_LBS",
]


def main():
    print("Quadpod runtime field tuning")
    print("============================")
    for name in FIELD_NAMES:
        print(f"{name}={getattr(config, name)}")

    print("\nPRELOAD_AUTO_TENSION_STAGES=")
    for threshold, speed, pulse in config.PRELOAD_AUTO_TENSION_STAGES:
        print(f"  {threshold:g} lb -> {speed}% for {pulse:g}s")

    loaded_thresholds = [stage[0] for stage in config.PRELOAD_AUTO_TENSION_STAGES]
    default_thresholds = [stage[0] for stage in config.DEFAULT_PRELOAD_AUTO_TENSION_STAGES]
    if loaded_thresholds != default_thresholds:
        print("\nWARNING: auto tension stage thresholds differ from code defaults.")


if __name__ == "__main__":
    main()
