#!/usr/bin/env python3
"""Print the active non-secret Quadpod field tuning values."""

import sys
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def load_env_file(path):
    if not path.exists():
        return False
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())
    return True


ENV_FILE = Path(os.getenv("QUADPOD_ENV_FILE", "/etc/quadpod.env"))
ENV_FILE_LOADED = load_env_file(ENV_FILE)

import config  # noqa: E402


FIELD_NAMES = [
    "LOADCELL_REFERENCE_UNIT",
    "LOADCELL_LIVENESS_WINDOW",
    "LOADCELL_GLITCH_REJECT",
    "LOADCELL_GLITCH_MAX_JUMP_LBS",
    "LOADCELL_GLITCH_MAX_CONSECUTIVE",
    "LOADCELL_GLITCH_MAX_RESETS",
    "SAMPLE_RATE_HZ",
    "VICTOR_NEUTRAL_US",
    "VICTOR_PULL_US",
    "VICTOR_JOG_US",
    "ACTUATOR_PULL_DIRECTION",
    "PULL_TARGET_IN_PER_MIN",
    "PRELOAD_TARGET_LBS",
    "PRELOAD_MIN_LBS",
    "PRELOAD_MAX_LBS",
    "PRELOAD_AUTO_ABORT_LBS",
    "PRELOAD_STABILITY_SECONDS",
    "PRELOAD_AUTO_TIMEOUT_SECONDS",
    "PRELOAD_AUTO_SPEED_PERCENT",
    "PRELOAD_AUTO_MIN_PULSE_SECONDS",
    "PRELOAD_AUTO_PULSE_SECONDS",
    "PRELOAD_AUTO_PULSE_CHECK_SECONDS",
    "PRELOAD_AUTO_DIRECT_LOAD_READ",
    "PRELOAD_AUTO_STOP_DURING_LOAD_READ",
    "PRELOAD_AUTO_CONTROL_CONFIRM_SAMPLES",
    "PRELOAD_AUTO_CONTROL_MIN_VALID_LBS",
    "PRELOAD_AUTO_CONTROL_MAX_VALID_LBS",
    "PRELOAD_AUTO_CONTROL_SPIKE_DELTA_LBS",
    "PRELOAD_AUTO_CONTROL_CONFIRM_MAX_RANGE_LBS",
    "PRELOAD_AUTO_CONTROL_HARD_SPIKE_LBS",
    "PRELOAD_AUTO_CONTROL_SPIKE_RETRY_SECONDS",
    "PRELOAD_AUTO_CONTROL_MAX_TRANSIENT_REJECTS",
    "PRELOAD_AUTO_MOVING_CONTROL_SAMPLES",
    "PRELOAD_AUTO_MODE",
    "PRELOAD_AUTO_CONTINUOUS_INTERVAL_SECONDS",
    "PRELOAD_AUTO_CONTINUOUS_POLL_SECONDS",
    "PRELOAD_AUTO_CONTINUOUS_MIN_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_MAX_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_KP",
    "PRELOAD_AUTO_CONTINUOUS_KD",
    "PRELOAD_AUTO_CONTINUOUS_RAMP_PERCENT_PER_SECOND",
    "PRELOAD_AUTO_CONTINUOUS_BRAKE_MARGIN_LBS",
    "PRELOAD_AUTO_CONTINUOUS_SLOWDOWN_LBS",
    "PRELOAD_AUTO_CONTINUOUS_MAX_UP_RATE_LBS_PER_SECOND",
    "PRELOAD_AUTO_CONTINUOUS_SENSOR_PACE_CRAWL_LBS",
    "PRELOAD_AUTO_CONTINUOUS_SENSOR_PACE_START_MAX_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_SENSOR_PACE_EARLY_MAX_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_SENSOR_PACE_MID_MAX_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_SENSOR_PACE_APPROACH_MAX_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_SENSOR_PACE_FINAL_MAX_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_SENSOR_PACE_FINE_MAX_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_SENSOR_PACE_CRAWL_MAX_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_FINAL_PULL_FLOOR_START_LBS",
    "PRELOAD_AUTO_CONTINUOUS_FINAL_PULL_MIN_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_FINAL_PULL_STOP_MARGIN_LBS",
    "PRELOAD_AUTO_CONTINUOUS_CRAWL_ZONE_LBS",
    "PRELOAD_AUTO_CONTINUOUS_CRAWL_MIN_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_CRAWL_MAX_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTINUOUS_CRAWL_STOP_SPEED_PERCENT",
    "PRELOAD_HOLD_TRIM_ENABLED",
    "PRELOAD_HOLD_TRIM_INTERVAL_SECONDS",
    "PRELOAD_HOLD_TRIM_STEP_US",
    "PRELOAD_HOLD_TRIM_MAX_US",
    "PRELOAD_HOLD_TRIM_DROP_RATE_LBS_PER_SECOND",
    "PRELOAD_AUTO_DOWN_PULSE_SECONDS",
    "PRELOAD_AUTO_SETTLE_SECONDS",
    "PRELOAD_AUTO_SETTLE_MAX_SECONDS",
    "PRELOAD_AUTO_TARGET_LBS",
    "PRELOAD_AUTO_FINAL_APPROACH_STOP_LBS",
    "PRELOAD_AUTO_FINAL_REBRAKE_MARGIN_LBS",
    "PRELOAD_AUTO_PREDICT_STOP_LBS",
    "PRELOAD_AUTO_PREDICT_ENABLE_LBS",
    "PRELOAD_AUTO_PREDICT_LOOKAHEAD_SECONDS",
    "PRELOAD_AUTO_RATE_WINDOW_SECONDS",
    "PRELOAD_AUTO_MAX_RISE_RATE_LBS_PER_SECOND",
    "PRELOAD_GLIDE_TARGET_LBS",
    "PRELOAD_GLIDE_READY_CEILING_LBS",
    "PRELOAD_GLIDE_OVERSHOOT_LBS",
    "PRELOAD_GLIDE_SEATED_FLOOR_LBS",
    "PRELOAD_GLIDE_MIN_MOVE_PCT",
    "PRELOAD_GLIDE_MAX_PCT",
    "PRELOAD_GLIDE_EASE_MARGIN_LBS",
    "PRELOAD_GLIDE_CRAWL_PCT",
    "PRELOAD_GLIDE_LOOKAHEAD_S",
    "PRELOAD_GLIDE_EMA_ALPHA",
    "PRELOAD_GLIDE_STABLE_S",
    "PRELOAD_GLIDE_STABLE_LBS",
    "PRELOAD_GLIDE_TIMEOUT_S",
    "PRELOAD_GLIDE_HOLD_AFTER",
    "PRELOAD_GLIDE_HOLD_SETTLE_S",
    "PRELOAD_GLIDE_HOLD_AIM_LO_LBS",
    "PRELOAD_GLIDE_HOLD_AIM_HI_LBS",
    "PRELOAD_GLIDE_HOLD_PULSE_US",
    "PRELOAD_GLIDE_HOLD_PULSE_MIN_US",
    "PRELOAD_GLIDE_HOLD_PULSE_MAX_US",
    "PRELOAD_GLIDE_HOLD_PULSE_MS",
    "PRELOAD_GLIDE_HOLD_PULSE_MS_MAX",
    "PRELOAD_GLIDE_HOLD_REST_S",
    "PRELOAD_GLIDE_HOLD_MAX_ITERS",
    "PRELOAD_GLIDE_HOLD_ABORT_LBS",
    "PRELOAD_GLIDE_HOLD_GENTLE_GAP_LBS",
    "PRELOAD_GLIDE_HOLD_TIMEOUT_S",
    "PRELOAD_AUTO_COARSE_MAX_DELTA_LBS",
    "PRELOAD_AUTO_APPROACH_MAX_DELTA_LBS",
    "PRELOAD_AUTO_FINAL_MAX_DELTA_LBS",
    "PRELOAD_AUTO_CONTACT_DELTA_LBS",
    "PRELOAD_AUTO_CONTACT_MAX_DELTA_LBS",
    "PRELOAD_AUTO_CONTACT_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTACT_PULSE_SECONDS",
    "PRELOAD_AUTO_CONTACT_SETTLE_SECONDS",
    "PRELOAD_AUTO_CONTACT_SETTLE_MAX_SECONDS",
    "PRELOAD_AUTO_CONTACT_MODE_START_LBS",
    "PRELOAD_AUTO_CONTACT_COARSE_SPEED_PERCENT",
    "PRELOAD_AUTO_CONTACT_COARSE_PULSE_SECONDS",
    "PRELOAD_AUTO_CONTACT_COARSE_MAX_DELTA_LBS",
    "PRELOAD_AUTO_MIN_STOP_MARGIN_LBS",
    "PRELOAD_AUTO_MAX_STOP_MARGIN_LBS",
    "PRELOAD_AUTO_COAST_MARGIN_SCALE",
    "PRELOAD_AUTO_ADAPTIVE_PULSE_MIN_SCALE",
    "PRELOAD_AUTO_ADAPTIVE_SPEED_MIN_PERCENT",
    "PRELOAD_AUTO_APPROACH_DISTANCE_LBS",
    "PRELOAD_AUTO_COARSE_UNTIL_LBS",
    "PRELOAD_AUTO_COARSE_SETTLE_SECONDS",
    "PRELOAD_AUTO_COARSE_SETTLE_MAX_SECONDS",
    "PRELOAD_AUTO_APPROACH_SETTLE_UNTIL_LBS",
    "PRELOAD_AUTO_APPROACH_SETTLE_SECONDS",
    "PRELOAD_AUTO_APPROACH_SETTLE_MAX_SECONDS",
    "PRELOAD_AUTO_APPROACH_SETTLE_DELTA_LBS",
    "PRELOAD_AUTO_STABLE_WINDOW_SECONDS",
    "PRELOAD_AUTO_STABLE_DELTA_LBS",
    "PRELOAD_AUTO_IN_BAND_END_SECONDS",
    "PRELOAD_AUTO_NEAR_BAND_HOLD_MARGIN_LBS",
    "PRELOAD_AUTO_NEAR_BAND_DROP_REJECT_LBS",
    "PRELOAD_AUTO_NEGATIVE_JUMP_GUARD_START_LBS",
    "PRELOAD_AUTO_NEGATIVE_JUMP_DELTA_LBS",
    "PRELOAD_AUTO_DRIFT_WINDOW_SECONDS",
    "PRELOAD_AUTO_DRIFT_MAX_DROP_LBS",
    "PRELOAD_AUTO_DRIFT_WARN_SECONDS",
    "PRELOAD_AUTO_TRACE_MAX_ENTRIES",
    "FAILURE_DROP_LBS",
    "FAILURE_DROP_PERCENT",
    "FAILURE_CONFIRM_SAMPLES",
    "FAILURE_MIN_PEAK_LBS",
]


def main():
    print("Quadpod runtime field tuning")
    print("============================")
    print(f"env_file={ENV_FILE if ENV_FILE_LOADED else 'not loaded'}")
    for name in FIELD_NAMES:
        print(f"{name}={getattr(config, name)}")

    print("\nPRELOAD_AUTO_TENSION_STAGES=")
    for threshold, speed, pulse in config.PRELOAD_AUTO_TENSION_STAGES:
        print(f"  {threshold:g} lb -> {speed}% for {pulse:g}s")

    loaded_thresholds = [stage[0] for stage in config.PRELOAD_AUTO_TENSION_STAGES]
    default_thresholds = [stage[0] for stage in config.DEFAULT_PRELOAD_AUTO_TENSION_STAGES]
    if loaded_thresholds != default_thresholds:
        print("\nWARNING: auto tension stage thresholds differ from code defaults.")


if __name__ == "__main__":
    main()
